## Lesson 1 - Reading a Dataset

In [2]:
import pandas as pd
df = pd.read_csv("data.csv")

## Lesson 2 — Looking at Data
View first 5 rows

In [3]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

View last 5 rows

In [3]:
df.tail()

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

Random rows

Returns any 3 random rows.

In [12]:
df.sample(3)

    Duration          Date  Pulse  Maxpulse  Calories
13        60  '2020/12/13'    106       128     345.3
0         60  '2020/12/01'    110       130     409.1
12        60  '2020/12/12'    100       120     250.7

## Lesson 3 - Dataset Information

In [13]:
df.shape

(32, 5)

Column names

In [14]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

Data Types

In [15]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

Complete Information

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

## Lesson 4 - Basic Statistics

In [18]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

## Lesson 5 - Selecting Columns

Single column

In [22]:
df["Pulse"]

0     110
1     117
2     103
3     109
4     117
5     102
6     110
7     104
8     109
9      98
10    103
11    100
12    100
13    106
14    104
15     98
16     98
17    100
18     90
19    103
20     97
21    108
22    100
23    130
24    105
25    102
26    100
27     92
28    103
29    100
30    102
31     92
Name: Pulse, dtype: int64

Type

In [23]:
type(df["Pulse"])

pandas.core.series.Series

Multiple columns

In [24]:
df[["Pulse","Calories"]]

    Pulse  Calories
0     110     409.1
1     117     479.0
2     103     340.0
3     109     282.4
4     117     406.0
5     102     300.0
6     110     374.0
7     104     253.3
8     109     195.1
9      98     269.0
10    103     329.3
11    100     250.7
12    100     250.7
13    106     345.3
14    104     379.3
15     98     275.0
16     98     215.2
17    100     300.0
18     90       NaN
19    103     323.0
20     97     243.0
21    108     364.2
22    100     282.0
23    130     300.0
24    105     246.0
25    102     334.5
26    100     250.0
27     92     241.0
28    103       NaN
29    100     280.0
30    102     380.3
31     92     243.0

## Lesson 6 - Selecting Rows

In [25]:
df.iloc[0] # first row

Duration              60
Date        '2020/12/01'
Pulse                110
Maxpulse             130
Calories           409.1
Name: 0, dtype: object

In [26]:
df.iloc[4] # fifth row

Duration              45
Date        '2020/12/05'
Pulse                117
Maxpulse             148
Calories           406.0
Name: 4, dtype: object

In [27]:
df.iloc[5:11] # Rows 5-10

    Duration          Date  Pulse  Maxpulse  Calories
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3

In [28]:
df.iloc[0:5,0:3] # Rows and Columns
# Rows 0–4
# Columns 0–2

   Duration          Date  Pulse
0        60  '2020/12/01'    110
1        60  '2020/12/02'    117
2        60  '2020/12/03'    103
3        45  '2020/12/04'    109
4        45  '2020/12/05'    117

## Lesson 7 - Access a Specific Value

In [31]:
df.loc[0, "Pulse"]

np.int64(110)

In [ ]:
df.loc[10, "Calories"]

## Difference between loc and iloc

iloc → works with position (index numbers)

df.iloc[0]

loc → works with labels (column names/index labels)

df.loc[0, "Pulse"]

This distinction becomes much more useful when your index isn't just 0, 1, 2, ...